# Generated by Django 4.2.19 on 2025-02-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSRouteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route_table_id', models.CharField(max_length=255)),
                ('vpc', models.CharField(max_length=255)),
                ('vpc_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AWSSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subnet_id', models.CharField(max_length=255)),
                ('vpc', models.CharField(max_length=255)),
                ('ipv4_cidr', models.CharField(max_length=255)),
                ('available_ipv4_address', models.IntegerField()),
                ('route_table', models.CharField(max_length=255)),
                ('vpc_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AWSVPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vpc_id', models.CharField(max_length=255)),
                ('ipv4_cidr', models.CharField(max_length=255)),
                ('main_route_table', models.CharField(max_length=255)),
                ('main_network_acl', models.CharField(max_length=255)),
                ('owner_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AzureRouteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_prefix', models.CharField(max_length=255)),
                ('next_hop_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AzureSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ipv4', models.CharField(max_length=255)),
                ('available_ips', models.IntegerField()),
                ('secret_group', models.CharField(max_length=255)),
                ('route_table', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AzureVirtualNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_group', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('subscription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AzureVnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_space', models.CharField(max_length=255)),
                ('subnets', models.CharField(max_length=255)),
                ('peerings', models.CharField(max_length=255)),
            ],
        ),
    ]
