# Generated by Django 4.2.19 on 2025-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_lookup_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsroutetable',
            name='routes',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='awsroutetable',
            name='status',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='awsroutetable',
            name='targets',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
