# Generated by Django 4.2.19 on 2025-02-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip_lookup_app', '0002_awsroutetable_routes_awsroutetable_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awsroutetable',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='awsroutetable',
            name='status',
        ),
        migrations.RemoveField(
            model_name='awsroutetable',
            name='targets',
        ),
        migrations.AlterField(
            model_name='awsroutetable',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='awsroutetable',
            name='vpc',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='awsroutetable',
            name='vpc_id',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.CreateModel(
            name='AWSRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_cidr_block', models.CharField(default='N/A', max_length=255)),
                ('target', models.CharField(default='N/A', max_length=255)),
                ('status', models.CharField(default='N/A', max_length=255)),
                ('route_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='ip_lookup_app.awsroutetable')),
            ],
        ),
    ]
