# Generated by Django 4.2.19 on 2025-02-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_lookup_app', '0003_remove_awsroutetable_routes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSEC2Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('vpc_id', models.CharField(max_length=50)),
                ('subnet_id', models.CharField(max_length=50)),
                ('private_ips', models.TextField(blank=True, null=True)),
                ('public_ips', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=20)),
                ('instance_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='awsvpc',
            name='ipv4_cidr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='awsvpc',
            name='main_network_acl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awsvpc',
            name='main_route_table',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awsvpc',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='awsvpc',
            name='owner_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='awsvpc',
            name='vpc_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
