# Generated by Django 4.2.19 on 2025-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_lookup_app', '0004_awsec2instance_alter_awsvpc_ipv4_cidr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsec2instance',
            name='region',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='awsroute',
            name='region',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='awsroutetable',
            name='region',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='awssubnet',
            name='region',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='awsvpc',
            name='region',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
