# Generated by Django 4.2.19 on 2025-02-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_lookup_app', '0005_awsec2instance_region_awsroute_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsec2instance',
            name='security_groups',
            field=models.JSONField(default=list),
        ),
    ]
