# Generated by Django 4.2.19 on 2025-02-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_lookup_app', '0006_awsec2instance_security_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSSecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='awsec2instance',
            name='security_groups',
        ),
        migrations.AddField(
            model_name='awsec2instance',
            name='security_groups',
            field=models.ManyToManyField(to='ip_lookup_app.awssecuritygroup'),
        ),
    ]
