# Generated by Django 4.2.19 on 2025-02-24 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip_lookup_app', '0008_awssecuritygroup_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSSecurityGroupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('ip_protocol', models.CharField(blank=True, max_length=20, null=True)),
                ('from_port', models.IntegerField(blank=True, null=True)),
                ('to_port', models.IntegerField(blank=True, null=True)),
                ('cidr_ipv4', models.CharField(blank=True, max_length=50, null=True)),
                ('cidr_ipv6', models.CharField(blank=True, max_length=50, null=True)),
                ('rule_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rule_description', models.CharField(blank=True, max_length=255, null=True)),
                ('security_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ip_lookup_app.awssecuritygroup')),
            ],
        ),
    ]
